"""
This is the template for the computation problem of computing a Groebner basis of an ideal
generated by a finite set of polynomials with integer coefficients (commutative). It creates
code for the computer algebra system Risa/Asir.

.. moduleauthor:: Albert Heinle <albert.heinle@uwaterloo.ca>
"""

#--------------------------------------------------
#---------------The template-----------------------
#--------------------------------------------------

def generateCode(vars, basis):
    """
    The main function generating the Risa/Asir code for the computation of
    the Groebner basis given the input variables.

    :param         vars: A list of variables used in the IntPS-System
    :type          vars: list
    :param        basis: The polynomials forming a basis of the IntPS-System. This input will not be checked whether
                         there are polynomials using variables not in the list of variables.
    :type         basis: list
    """
    result = """load("gr")$
B=[%s]$
print("=====Solution Begin=====");
print(gr(B,[%s],2));
print("=====Solution End=====");""" % (", ".join(basis), ",".join(vars))
    return result

#--------------------------------------------------
#----------------Help Functions--------------------
#--------------------------------------------------
